In [1]:
# Filtering out for Luma candidate

In [2]:
import pandas as pd
import os

In [3]:
luma_file = r"C:\Users\User\Downloads\reviews_Agentic_Engineering_Multi_Agent_Systems_Talks_AI_Agent_Workshops_Ft_Snowflake_Cognee.csv"

data = pd.read_csv(luma_file)

file_name = os.path.basename(luma_file)
file_name

'reviews_Agentic_Engineering_Multi_Agent_Systems_Talks_AI_Agent_Workshops_Ft_Snowflake_Cognee.csv'

In [4]:
data1= data[['name','linkedin', 'profile_review','relevant_profile','job_title_last_company', 'job_title_last_5_years', 
        'location','is_open_to_work', 'is_engaged_in_job_market', 'recent_job_change']]

In [5]:
# make format consistant to avoid any error, remove leading trailing space, capitalization

cols = [
    "profile_review",
    "relevant_profile",
    "job_title_last_company",
    "job_title_last_5_years"
]

data1[cols] = data1[cols].apply(lambda x: x.str.strip().str.title())

C:\Users\User\AppData\Local\Temp\ipykernel_15472\2803384331.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data1[cols] = data1[cols].apply(lambda x: x.str.strip().str.title())

In [ ]:
# filter out parameters

desired_profile_review = ["Good", "Elite"]
desired_relevant_profile_status = ["Yes"]

# list of role that we do not want
non_target_roles = [
    "advocate",
    "Advisor",
    "Analyst",
    "architect",
    "blockchain engineer",
    "Consultant",
    "creative lead",
    "Cybersecurity",
    "data engineer",
    "data product",
    "developer relations",
    "devrel",
    "director of engineering",
    "head of data",
    "just some guy",
    "Marketing",
    "Owner",
    "product",
    "professor",
    "program manager",
    "reliability engineer",
    "Solutions Engineer",
    "technical project manager"
]

In [7]:
# filter out byt profile_review 

data2 = data1[data1["profile_review"].isin(desired_profile_review)]                         # profile_review = Good, Elite

                
# filter out by relevant profile
data3 = data2[data2["relevant_profile"].isin(desired_relevant_profile_status)]              # relevant_profile = yes

In [8]:
data3.head()

,name,linkedin,profile_review,relevant_profile,job_title_last_company,job_title_last_5_years,location,is_open_to_work,is_engaged_in_job_market,recent_job_change
3,Jason Chen,https://www.linkedin.com/in/jasonjschen,Good,Yes,Senior Software Engineer,Software Engineer,San Francisco Bay Area,NaN,NaN,NO
4,Harshita Jhavar,https://www.linkedin.com/in/harshitajhavar,Good,Yes,Senior Machine Learning Data Scientist,Ai Engineer,"Cupertino, California, United States",NaN,NaN,NO
17,Mark Woh,https://linkedin.com/in/mark-woh-03803314,Good,Yes,System Architecture Lead / Senior Staff Silico...,Ai Engineer,"San Francisco, California, United States",0.0,NaN,NO
23,Avinash Kalivarapu,https://linkedin.com/in/avinashkali,Good,Yes,Software Engineer,Software Engineer,United States,0.0,NaN,YES
60,Sowmith Mandadi,https://www.linkedin.com/in/sowmithmandadi,Good,Yes,Senior Software Engineer,Software Engineer,"Sunnyvale, California, United States",0.0,NaN,NO

In [9]:
# substring matching

pattern = "|".join(role.lower() for role in non_target_roles)           # '|' --> OR; stores lowercase form of all non_target_roles in or ex. A|B|C


# remove: boolean; if any of the column has non desired target role then it mark as true


remove = (
    data3["job_title_last_company"].str.lower().str.contains(pattern, na=False) |       # na=False-->if value=NaN treat as not a match don't give error
    data3["job_title_last_5_years"].str.lower().str.contains(pattern, na=False)
)

In [10]:
# In case you want to check data that has been removed
# data3[remove]             gives complete data

# gte list of titles removed
removed_titles = data3[remove][[
    "job_title_last_company",
    "job_title_last_5_years"
]]

removed_titles

                                job_title_last_company job_title_last_5_years
4               Senior Machine Learning Data Scientist            Ai Engineer
17   System Architecture Lead / Senior Staff Silico...            Ai Engineer
109                            Director Of Engineering            Ai Engineer
122                        Ai Developer Relations Lead            Ai Engineer
520                           Co-Founder, Ai Architect            Ai Engineer

In [11]:

# filtered data

filtered_data = data3[remove == False]           # filter out all non non_target_roles 
                                                 # == False  keep the ones that don't contain those non target roles.
 
# check total filtered candidates
print("Total candidates:", len(filtered_data))

Total candidates: 32

In [12]:
print(file_name, "\n",)
filtered_data.head(10)

reviews_Agentic_Engineering_Multi_Agent_Systems_Talks_AI_Agent_Workshops_Ft_Snowflake_Cognee.csv

,name,linkedin,profile_review,relevant_profile,job_title_last_company,job_title_last_5_years,location,is_open_to_work,is_engaged_in_job_market,recent_job_change
3,Jason Chen,https://www.linkedin.com/in/jasonjschen,Good,Yes,Senior Software Engineer,Software Engineer,San Francisco Bay Area,NaN,NaN,NO
23,Avinash Kalivarapu,https://linkedin.com/in/avinashkali,Good,Yes,Software Engineer,Software Engineer,United States,0.0,NaN,YES
60,Sowmith Mandadi,https://www.linkedin.com/in/sowmithmandadi,Good,Yes,Senior Software Engineer,Software Engineer,"Sunnyvale, California, United States",0.0,NaN,NO
93,Shreya Reddy,https://www.linkedin.com/in/shreyaragireddy,Good,Yes,Software Engineer - Gcp,Software Engineer,"Sunnyvale, California, United States",0.0,NaN,NO
98,Adel Ahmadyan,https://www.linkedin.com/in/agentastic,Good,Yes,Software Engineer,Software Engineer,"San Francisco, California, United States",0.0,NaN,NO
141,Gavin Guo,https://www.linkedin.com/in/gavin-guo-b764b6b4,Good,Yes,Ai Research Scientist,Ai Engineer,"Menlo Park, California, United States",0.0,NaN,NO
172,Ankur A.,https://www.linkedin.com/in/agarwalankur9,Good,Yes,Engineering Leader - Software And Services,Software Engineer,San Francisco Bay Area,0.0,NaN,NO
175,Ryan Fong,https://www.linkedin.com/in/ryan-fong-254059122,Good,Yes,Software Development Engineer Ii,Software Engineer,"Millbrae, California, United States",0.0,NaN,NO
176,Shiqi Ai,https://www.linkedin.com/in/shiqiai,Good,Yes,Senior Software Engineer,Software Engineer,"San Mateo, California, United States",0.0,NaN,NO
228,Shaobai Jiang,https://www.linkedin.com/in/shaobaijiang,Good,Yes,Applied Scientist Ii,Ai Engineer,San Francisco Bay Area,0.0,0.0,NO

In [13]:
# get file saved
# filtered_data.to_csv("filtered_data.csv", index=False)

# Candidate Filter

## Overview

This filtering process identifies relevant profiles based on **Profile Review** (`Good`, `Elite`) and **Relevant Profile** status, while also filtering out non-target job roles using pattern matching. It allows you to see which roles were removed, track the total number of profiles filtered, validate the filtering results, and download the final filtered dataset for further use.



### Handling Job Title Variations with Pattern Matching

Initially, I used exact-match filtering, which required every job-title variation to be added separately. To overcome this limitation, I used substring/pattern matching so that a role such as `"Data Engineer"` also matches variations like `"Senior Data Engineer"`, `"Junior Data Engineer"`, and `"Data Engineer II"` without manually adding each variation.

### Boolean Mask for Testing

Instead of directly filtering the dataset, I created a `remove` Boolean mask that marks matching profiles as `True`. This allows me to create the final filtered dataset while also checking the profiles marked for removal to verify that the correct roles are being filtered.